# all options https://taplo.tamasfe.dev/configuration/formatter-options.html

# this dir uses some templating that makes toml invalid
exclude = ["polkadot/zombienet_tests/**"]

[formatting]
inline_table_expand = false
array_auto_expand = false
array_auto_collapse = false
indent_string = "	"         # tab
