[package]
name = "pallet-contracts-uapi"
version = "4.0.0-dev"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Exposes all the host functions that a contract can import."

[dependencies]
paste = { version = "1.0", default-features = false }
bitflags = "1.0"

